apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebeventappdevops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebeventappdevops
  template:
    metadata:
      labels:
        app: mywebeventappdevops
    spec:
      containers:
      - name: mywebeventappdevops
        image: gcr.io/mywebeventappdevops/mywebeventappdevops:latest
        ports:
        - containerPort: 8080