apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebeventappdevops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebeventappdevops
  template:
    metadata:
      labels:
        app: mywebeventappdevops
    spec:
      containers:
      - name: mywebeventappdevops
        image: gcr.io/mywebeventappdevops/mywebeventappdevops:latest
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata: 
  name: mywebeventappdevops
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 8080
  selector: 
    app: mywebeventappdevops
  type: LoadBalancer

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mywebeventappdevops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mywebeventappdevops
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60