apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebeventappdevops
spec:
  replicas: 3
  containers:
  - name: mywebeventappdevops
    image: mywebeventappdevops/mywebeventappdevops:latest
    ports:
    - containerPort: 8080

